[build]
  command = "hugo --gc --minify -b "$HUGO_BASEURL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify -b "$HUGO_BASEURL"

[context.branch-deploy]
  command = "hugo --gc --minify -b "$HUGO_BASEURL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
